/*
﻿Developed with the contribution of the European Commission - Directorate General for Maritime Affairs and Fisheries
© European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can
redistribute it and/or modify it under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or any later version. The IFDM Suite is distributed in
the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. You should have received a
copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 11:04:40 fm CEST 
//


package eu.europa.ec.fisheries.uvms.service.client.flux.movement.contract;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BasicAttributeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicAttributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageID" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:13}IDType"/>
 *         &lt;element name="Creation" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:13}DateTimeType"/>
 *         &lt;element name="ExchangeDocumentInfo" type="{urn:xeu:ec:fisheries:flux-bl:FLUXVesselPosition:1:1}ExchangeDocumentInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicAttributeType", namespace = "urn:xeu:ec:fisheries:flux-bl:FLUXVesselPosition:1:1", propOrder = {
    "messageID",
    "creation",
    "exchangeDocumentInfo"
})
@XmlRootElement(name = "BasicAttribute", namespace = "urn:xeu:ec:fisheries:flux-bl:FLUXVesselPosition:1:1")
public class BasicAttribute {

    @XmlElement(name = "MessageID", required = true)
    protected IDType messageID;
    @XmlElement(name = "Creation", required = true)
    protected XMLGregorianCalendar creation;
    @XmlElement(name = "ExchangeDocumentInfo", required = true)
    protected ExchangeDocumentInfoType exchangeDocumentInfo;

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setMessageID(IDType value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the creation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreation() {
        return creation;
    }

    /**
     * Sets the value of the creation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreation(XMLGregorianCalendar value) {
        this.creation = value;
    }

    /**
     * Gets the value of the exchangeDocumentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ExchangeDocumentInfoType }
     *     
     */
    public ExchangeDocumentInfoType getExchangeDocumentInfo() {
        return exchangeDocumentInfo;
    }

    /**
     * Sets the value of the exchangeDocumentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchangeDocumentInfoType }
     *     
     */
    public void setExchangeDocumentInfo(ExchangeDocumentInfoType value) {
        this.exchangeDocumentInfo = value;
    }

}