/*
﻿Developed with the contribution of the European Commission - Directorate General for Maritime Affairs and Fisheries
© European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can
redistribute it and/or modify it under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or any later version. The IFDM Suite is distributed in
the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. You should have received a
copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 11:04:40 fm CEST 
//


package eu.europa.ec.fisheries.uvms.service.client.flux.movement.contract;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExchangeDocumentInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExchangeDocumentInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actionType" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:13}CodeType"/>
 *         &lt;element name="editorType" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:13}TextType"/>
 *         &lt;element name="actionReason" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:13}TextType" minOccurs="0"/>
 *         &lt;element name="referenceMessageID" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:13}IDType" minOccurs="0"/>
 *         &lt;element name="VesselPosition" type="{urn:xeu:ec:fisheries:flux-bl:FLUXVesselPosition:1:1}VesselPositionType" maxOccurs="unbounded"/>
 *         &lt;element name="VesselID" type="{urn:xeu:ec:fisheries:flux-bl:FLUX_AggregateBusinessInformationEntity:1:1}VesselIdentificationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExchangeDocumentInfoType", namespace = "urn:xeu:ec:fisheries:flux-bl:FLUXVesselPosition:1:1", propOrder = {
    "actionType",
    "editorType",
    "actionReason",
    "referenceMessageID",
    "vesselPositions",
    "vesselID"
})
public class ExchangeDocumentInfoType {

    @XmlElement(required = true)
    protected CodeType actionType;
    @XmlElement(required = true)
    protected TextType editorType;
    protected TextType actionReason;
    protected IDType referenceMessageID;
    @XmlElement(name = "VesselPosition", required = true)
    protected List<VesselPositionType> vesselPositions;
    @XmlElement(name = "VesselID", required = true)
    protected VesselIdentificationType vesselID;

    /**
     * Gets the value of the actionType property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setActionType(CodeType value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the editorType property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getEditorType() {
        return editorType;
    }

    /**
     * Sets the value of the editorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setEditorType(TextType value) {
        this.editorType = value;
    }

    /**
     * Gets the value of the actionReason property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getActionReason() {
        return actionReason;
    }

    /**
     * Sets the value of the actionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setActionReason(TextType value) {
        this.actionReason = value;
    }

    /**
     * Gets the value of the referenceMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getReferenceMessageID() {
        return referenceMessageID;
    }

    /**
     * Sets the value of the referenceMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setReferenceMessageID(IDType value) {
        this.referenceMessageID = value;
    }

    /**
     * Gets the value of the vesselPositions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vesselPositions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVesselPositions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VesselPositionType }
     * 
     * 
     */
    public List<VesselPositionType> getVesselPositions() {
        if (vesselPositions == null) {
            vesselPositions = new ArrayList<VesselPositionType>();
        }
        return this.vesselPositions;
    }

    /**
     * Gets the value of the vesselID property.
     * 
     * @return
     *     possible object is
     *     {@link VesselIdentificationType }
     *     
     */
    public VesselIdentificationType getVesselID() {
        return vesselID;
    }

    /**
     * Sets the value of the vesselID property.
     * 
     * @param value
     *     allowed object is
     *     {@link VesselIdentificationType }
     *     
     */
    public void setVesselID(VesselIdentificationType value) {
        this.vesselID = value;
    }

}