//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.20 at 04:10:39 em CEST 
//


package eu.europa.ec.fisheries.uvms.service.client.flux.movement.contract;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.ec.fisheries.uvms.service.client.flux.movement.contract package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.ec.fisheries.uvms.service.client.flux.movement.contract
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FLUXGeographicalCoordinateType }
     * 
     */
    public FLUXGeographicalCoordinateType createFLUXGeographicalCoordinateType() {
        return new FLUXGeographicalCoordinateType();
    }

    /**
     * Create an instance of {@link VesselStorageCharacteristicType }
     * 
     */
    public VesselStorageCharacteristicType createVesselStorageCharacteristicType() {
        return new VesselStorageCharacteristicType();
    }

    /**
     * Create an instance of {@link WebsiteCommunicationType }
     * 
     */
    public WebsiteCommunicationType createWebsiteCommunicationType() {
        return new WebsiteCommunicationType();
    }

    /**
     * Create an instance of {@link VesselTechnicalCharacteristicType }
     * 
     */
    public VesselTechnicalCharacteristicType createVesselTechnicalCharacteristicType() {
        return new VesselTechnicalCharacteristicType();
    }

    /**
     * Create an instance of {@link TargetedQuotaType }
     * 
     */
    public TargetedQuotaType createTargetedQuotaType() {
        return new TargetedQuotaType();
    }

    /**
     * Create an instance of {@link ContactPartyType }
     * 
     */
    public ContactPartyType createContactPartyType() {
        return new ContactPartyType();
    }

    /**
     * Create an instance of {@link SpecifiedLinearRingType }
     * 
     */
    public SpecifiedLinearRingType createSpecifiedLinearRingType() {
        return new SpecifiedLinearRingType();
    }

    /**
     * Create an instance of {@link VesselDimensionType }
     * 
     */
    public VesselDimensionType createVesselDimensionType() {
        return new VesselDimensionType();
    }

    /**
     * Create an instance of {@link DateTimeType }
     * 
     */
    public DateTimeType createDateTimeType() {
        return new DateTimeType();
    }

    /**
     * Create an instance of {@link GearCharacteristicType }
     * 
     */
    public GearCharacteristicType createGearCharacteristicType() {
        return new GearCharacteristicType();
    }

    /**
     * Create an instance of {@link EmailCommunicationType }
     * 
     */
    public EmailCommunicationType createEmailCommunicationType() {
        return new EmailCommunicationType();
    }

    /**
     * Create an instance of {@link FishingGearType }
     * 
     */
    public FishingGearType createFishingGearType() {
        return new FishingGearType();
    }

    /**
     * Create an instance of {@link SpecifiedPolygonType }
     * 
     */
    public SpecifiedPolygonType createSpecifiedPolygonType() {
        return new SpecifiedPolygonType();
    }

    /**
     * Create an instance of {@link FLUXPartyType }
     * 
     */
    public FLUXPartyType createFLUXPartyType() {
        return new FLUXPartyType();
    }

    /**
     * Create an instance of {@link VesselEngineType }
     * 
     */
    public VesselEngineType createVesselEngineType() {
        return new VesselEngineType();
    }

    /**
     * Create an instance of {@link ConstructionEventType }
     * 
     */
    public ConstructionEventType createConstructionEventType() {
        return new ConstructionEventType();
    }

    /**
     * Create an instance of {@link FLUXPictureType }
     * 
     */
    public FLUXPictureType createFLUXPictureType() {
        return new FLUXPictureType();
    }

    /**
     * Create an instance of {@link IDType }
     * 
     */
    public IDType createIDType() {
        return new IDType();
    }

    /**
     * Create an instance of {@link SpecifiedPreferenceType }
     * 
     */
    public SpecifiedPreferenceType createSpecifiedPreferenceType() {
        return new SpecifiedPreferenceType();
    }

    /**
     * Create an instance of {@link VesselEquipmentCharacteristicType }
     * 
     */
    public VesselEquipmentCharacteristicType createVesselEquipmentCharacteristicType() {
        return new VesselEquipmentCharacteristicType();
    }

    /**
     * Create an instance of {@link VesselAdministrativeCharacteristicType }
     * 
     */
    public VesselAdministrativeCharacteristicType createVesselAdministrativeCharacteristicType() {
        return new VesselAdministrativeCharacteristicType();
    }

    /**
     * Create an instance of {@link VesselPositionEventType }
     * 
     */
    public VesselPositionEventType createVesselPositionEventType() {
        return new VesselPositionEventType();
    }

    /**
     * Create an instance of {@link DelimitedPeriodType }
     * 
     */
    public DelimitedPeriodType createDelimitedPeriodType() {
        return new DelimitedPeriodType();
    }

    /**
     * Create an instance of {@link FLAPDocumentType }
     * 
     */
    public FLAPDocumentType createFLAPDocumentType() {
        return new FLAPDocumentType();
    }

    /**
     * Create an instance of {@link BinaryObjectType }
     * 
     */
    public BinaryObjectType createBinaryObjectType() {
        return new BinaryObjectType();
    }

    /**
     * Create an instance of {@link FishingCategoryType }
     * 
     */
    public FishingCategoryType createFishingCategoryType() {
        return new FishingCategoryType();
    }

    /**
     * Create an instance of {@link VesselTransportCharterType }
     * 
     */
    public VesselTransportCharterType createVesselTransportCharterType() {
        return new VesselTransportCharterType();
    }

    /**
     * Create an instance of {@link FLUXCharacteristicType }
     * 
     */
    public FLUXCharacteristicType createFLUXCharacteristicType() {
        return new FLUXCharacteristicType();
    }

    /**
     * Create an instance of {@link StructuredAddressType }
     * 
     */
    public StructuredAddressType createStructuredAddressType() {
        return new StructuredAddressType();
    }

    /**
     * Create an instance of {@link SpecifiedPeriodType }
     * 
     */
    public SpecifiedPeriodType createSpecifiedPeriodType() {
        return new SpecifiedPeriodType();
    }

    /**
     * Create an instance of {@link SpecifiedDirectPositionType }
     * 
     */
    public SpecifiedDirectPositionType createSpecifiedDirectPositionType() {
        return new SpecifiedDirectPositionType();
    }

    /**
     * Create an instance of {@link VesselTransportMeansType }
     * 
     */
    public VesselTransportMeansType createVesselTransportMeansType() {
        return new VesselTransportMeansType();
    }

    /**
     * Create an instance of {@link IndicatorType }
     * 
     */
    public IndicatorType createIndicatorType() {
        return new IndicatorType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link ConstructionLocationType }
     * 
     */
    public ConstructionLocationType createConstructionLocationType() {
        return new ConstructionLocationType();
    }

    /**
     * Create an instance of {@link MeasureType }
     * 
     */
    public MeasureType createMeasureType() {
        return new MeasureType();
    }

    /**
     * Create an instance of {@link QuantityType }
     * 
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link AuthorizationStatusType }
     * 
     */
    public AuthorizationStatusType createAuthorizationStatusType() {
        return new AuthorizationStatusType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link FLUXBinaryFileType }
     * 
     */
    public FLUXBinaryFileType createFLUXBinaryFileType() {
        return new FLUXBinaryFileType();
    }

    /**
     * Create an instance of {@link FLUXLocationType }
     * 
     */
    public FLUXLocationType createFLUXLocationType() {
        return new FLUXLocationType();
    }

    /**
     * Create an instance of {@link VesselCrewType }
     * 
     */
    public VesselCrewType createVesselCrewType() {
        return new VesselCrewType();
    }

    /**
     * Create an instance of {@link TelecommunicationCommunicationType }
     * 
     */
    public TelecommunicationCommunicationType createTelecommunicationCommunicationType() {
        return new TelecommunicationCommunicationType();
    }

    /**
     * Create an instance of {@link ValidationResultDocumentType }
     * 
     */
    public ValidationResultDocumentType createValidationResultDocumentType() {
        return new ValidationResultDocumentType();
    }

    /**
     * Create an instance of {@link NumericType }
     * 
     */
    public NumericType createNumericType() {
        return new NumericType();
    }

    /**
     * Create an instance of {@link VesselCountryType }
     * 
     */
    public VesselCountryType createVesselCountryType() {
        return new VesselCountryType();
    }

    /**
     * Create an instance of {@link FLUXReportDocumentType }
     * 
     */
    public FLUXReportDocumentType createFLUXReportDocumentType() {
        return new FLUXReportDocumentType();
    }

    /**
     * Create an instance of {@link FLUXVesselPositionMessage }
     * 
     */
    public FLUXVesselPositionMessage createFLUXVesselPositionMessage() {
        return new FLUXVesselPositionMessage();
    }

    /**
     * Create an instance of {@link ValidationQualityAnalysisType }
     * 
     */
    public ValidationQualityAnalysisType createValidationQualityAnalysisType() {
        return new ValidationQualityAnalysisType();
    }

    /**
     * Create an instance of {@link RegistrationLocationType }
     * 
     */
    public RegistrationLocationType createRegistrationLocationType() {
        return new RegistrationLocationType();
    }

    /**
     * Create an instance of {@link RegistrationEventType }
     * 
     */
    public RegistrationEventType createRegistrationEventType() {
        return new RegistrationEventType();
    }

    /**
     * Create an instance of {@link FLAPRequestDocumentType }
     * 
     */
    public FLAPRequestDocumentType createFLAPRequestDocumentType() {
        return new FLAPRequestDocumentType();
    }

    /**
     * Create an instance of {@link ContactPersonType }
     * 
     */
    public ContactPersonType createContactPersonType() {
        return new ContactPersonType();
    }

    /**
     * Create an instance of {@link VesselGeographicalCoordinateType }
     * 
     */
    public VesselGeographicalCoordinateType createVesselGeographicalCoordinateType() {
        return new VesselGeographicalCoordinateType();
    }

}
