/*
﻿Developed with the contribution of the European Commission - Directorate General for Maritime Affairs and Fisheries
© European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can
redistribute it and/or modify it under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or any later version. The IFDM Suite is distributed in
the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. You should have received a
copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 11:04:40 fm CEST 
//


package eu.europa.ec.fisheries.uvms.service.client.flux.movement.contract;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VesselIdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VesselIdentificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FlagState" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:13}CodeType"/>
 *         &lt;element name="UVI" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:13}IDType" minOccurs="0"/>
 *         &lt;element name="regionalID" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:13}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExternalMarking" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:13}IDType" minOccurs="0"/>
 *         &lt;element name="RadioCallSign" type="{urn:un:unece:uncefact:data:standard:UnqualifiedDataType:13}IDType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VesselIdentificationType", namespace = "urn:xeu:ec:fisheries:flux-bl:FLUX_AggregateBusinessInformationEntity:1:1", propOrder = {
    "flagState",
    "uvi",
    "regionalIDs",
    "externalMarking",
    "radioCallSign"
})
public class VesselIdentificationType {

    @XmlElement(name = "FlagState", required = true)
    protected CodeType flagState;
    @XmlElement(name = "UVI")
    protected IDType uvi;
    @XmlElement(name = "regionalID")
    protected List<IDType> regionalIDs;
    @XmlElement(name = "ExternalMarking")
    protected IDType externalMarking;
    @XmlElement(name = "RadioCallSign")
    protected IDType radioCallSign;

    /**
     * Gets the value of the flagState property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getFlagState() {
        return flagState;
    }

    /**
     * Sets the value of the flagState property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setFlagState(CodeType value) {
        this.flagState = value;
    }

    /**
     * Gets the value of the uvi property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getUVI() {
        return uvi;
    }

    /**
     * Sets the value of the uvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setUVI(IDType value) {
        this.uvi = value;
    }

    /**
     * Gets the value of the regionalIDs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regionalIDs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegionalIDs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getRegionalIDs() {
        if (regionalIDs == null) {
            regionalIDs = new ArrayList<IDType>();
        }
        return this.regionalIDs;
    }

    /**
     * Gets the value of the externalMarking property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getExternalMarking() {
        return externalMarking;
    }

    /**
     * Sets the value of the externalMarking property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setExternalMarking(IDType value) {
        this.externalMarking = value;
    }

    /**
     * Gets the value of the radioCallSign property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getRadioCallSign() {
        return radioCallSign;
    }

    /**
     * Sets the value of the radioCallSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setRadioCallSign(IDType value) {
        this.radioCallSign = value;
    }

}