/*
﻿Developed with the contribution of the European Commission - Directorate General for Maritime Affairs and Fisheries
© European Union, 2015-2016.

This file is part of the Integrated Fisheries Data Management (IFDM) Suite. The IFDM Suite is free software: you can
redistribute it and/or modify it under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or any later version. The IFDM Suite is distributed in
the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. You should have received a
copy of the GNU General Public License along with the IFDM Suite. If not, see <http://www.gnu.org/licenses/>.
 */
package xeu.connector_bridge.wsdl.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2016-01-29T13:39:47.737+01:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "urn:xeu:connector-bridge:wsdl:v1", name = "BridgeConnectorPortType")
@XmlSeeAlso({xeu.connector_bridge.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BridgeConnectorPortType {

    @WebResult(name = "POSTMSGOUT", targetNamespace = "urn:xeu:connector-bridge:v1", partName = "output")
    @WebMethod(action = "urn:xeu:connector-bridge:wsdl:v1:post")
    public xeu.connector_bridge.v1.PostMsgOutType post(
        @WebParam(partName = "parameter", name = "POSTMSG", targetNamespace = "urn:xeu:connector-bridge:v1")
        xeu.connector_bridge.v1.PostMsgType parameter
    );
}